"""update product schema

Revision ID: c3673dff69b7
Revises: 
Create Date: 2023-05-04 19:31:35.787286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3673dff69b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('country_of_origin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('country_of_origin')
        batch_op.drop_column('abv')

    # ### end Alembic commands ###
